# - name: Add MariaDB Repository
#  become: yes
#  yum_repository:
#    name: MariaDB
#    description: RPM_MARIA
#    baseurl: http://yum.mariadb.org/10.1/centos7-amd64
#    gpgcheck: no


- name: "Install pachage base"
  become: yes
  package:
    name: "{{ item }}"
  with_items:
    - "curl"
    - "gcc"
    - "gcc-c++"
    - "make "
    - "python-devel"
    - "expect" 
    - "wget" 
    - "cyrus-sasl-devel"
    - "postgresql"
    - "postgresql-server"

- name: "Install pachage base Centos"
  become: yes
  package:
    name: "{{ item }}"
  with_items:
    - "supervisor"
    - "nginx"
    - "python-pip"
    - "python2-pip"
  when: ansible_distribution == 'CentOS'


- name: "Install pachage base Redaht"
  become: yes
  package:
    name: "{{ item }}"
  with_items:
  - "rh-nginx112"
  - "python27-python-pip"
  - "rh-redis32"
  - "python27-python-devel"
  when: ansible_distribution  | lower == 'redhat'


- yum: name={{ item }}
  become: yes
  with_items:
  - https://download.emercoin.com/rhel/el7/RPMS/python-meld3-0.6.10-1.el7.x86_64.rpm
  - https://download.emercoin.com/rhel/el7/RPMS/supervisor-3.1.3-3.el7.noarch.rpm
  when: ansible_distribution  | lower == 'redhat'


#- name: "Install MariaDB"
#  become: yes
# package:
#   name: "{{ item }}"
# with_items:
#   - "MariaDB-devel"



- name: "install sasl lib dev"
  become: yes
  package:
    name: "{{ item }}"
  with_items:
    - "cyrus-sasl-md5"
    - "cyrus-sasl-gssapi"
  ignore_errors: yes


- name: enable and start the redis server
  become: yes
  service: name=redis enabled=yes state=started
  when: ansible_distribution == 'CentOS'

- name: enable and start the redis server
  become: yes
  service: name=rh-redis32-redis enabled=yes state=started
  when: ansible_distribution  | lower == 'redhat'


