---
- name: remode default ngix
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy Supervisord configuration Centos
  become: yes
  template:
    src: nginx.conf 
    dest: /etc/nginx/nginx.conf 
  when: ansible_distribution  | lower == 'centos'


- name: Copy Supervisord configuration RH
  become: yes
  template:
    src: nginx.conf
    dest:  /etc/opt/rh/rh-nginx112/nginx/nginx.conf
  when: ansible_distribution  | lower == 'redhat'


- name: Copy Supervisord configuration
  become: yes
  template:
    src: nginx_redash_site
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - restart nginx
#  when: ansible_distribution  | lower == 'centos'


#- name: Copy Supervisord configuration
#  become: yes
#  template:
#    src: nginx_redash_site
#    dest: /etc/opt/rh/rh-nginx112/nginx/nginx.conf.default
#  notify:
#    - restart nginx
#  when: ansible_distribution  | lower == 'redhat'

- name: set "httpd_can_network_connect" flag on
  become: yes
  seboolean: name={{ item }} state=yes persistent=yes
  with_items:
    - httpd_can_network_connect


- name: enable and start the nginx server
  become: yes
  service: name=nginx enabled=yes state=started
